# Generated by Django 2.2.6 on 2019-11-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Comout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Comin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person')),
            ],
        ),
    ]
