# Generated by Django 2.2.6 on 2019-11-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comin',
            options={'verbose_name': 'Время прихода на работу', 'verbose_name_plural': 'Время прихода на работу'},
        ),
        migrations.AlterModelOptions(
            name='comout',
            options={'verbose_name': 'Время ухода на работу', 'verbose_name_plural': 'Время ухода на работу'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
