# Generated by Django 2.2.6 on 2019-12-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191121_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comout',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='person_id',
        ),
        migrations.DeleteModel(
            name='Comin',
        ),
        migrations.DeleteModel(
            name='Comout',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
